### PR TITLE
fix seek bar tooltip display

### PR DESCRIPTION
**Pull request by nomo-kazza**

### CODE REVIEW

**Comment by hozefaj** [comment]
Can you put a working example somewhere to see? Maybe using [codesanbox](https://codesandbox.io/)?

**Comment by nomo-kazza** [comment]
I have created the example and deployed to Heroku https://accessible-html5-video-player.herokuapp.com/index.html, codesandbox seems not working for me.

**Comment by hozefaj** [comment]
Looks good 👍 Thanks

**Comment by hozefaj** [comment]
Fixes #110

**Comment by gody1001** [comment]
Seek tooltip

**Pull request merged**
