### PR TITLE
add responsiveness. support svg controls. #76

### PR DESCRIPTION
**Pull request by mreinstein**
Merged all of the code changes from https://source.ind.ie/project/video-player back into this original project (except for the license changes and branding which remain the same.)

Let me know if you have any issues or changes that you need prior to merging, happy to help!

### CODE REVIEW

**Comment by mreinstein** [comment]
@hozefaj any thoughts on this PR, something that we're interested in? I'm happy to make changes if this is along the right track.

**Comment by hozefaj** [comment]
@mreinstein do you have a demo of the code running somewhere? I want to take a look at the working version of the code.

**Comment by mreinstein** [comment]
@hozefaj it's running here https://awesome-kxqnswpjbt.now.sh/docs/

**Comment by mreinstein** [comment]
@hozefaj if it's desirable I could try to pull support for non-flexbox and non-svg browsers (< ie10.) That would remove the need for modernizr as a dependency.

Initially I was trying to be conservative and just match what the indie player fork did.

**Comment by hozefaj** [comment]
Actually I would prefer. Would make the code smaller and more easy to update going forward.

**Comment by mreinstein** [comment]
@hozefaj I've updated to remove modernizr and the legacy png based spritesheet (svg only now.)

I've tested in ie10+.  Public test url is available here: https://accessible-html5-video-player-bfpasimzkh.now.sh

**Comment by hozefaj** [comment]
LGTM!!

**Pull request merged**
