### PR TITLE
Multiple Text Track Support

### PR DESCRIPTION
**Pull request by shanepoints**
Adding support  for multiple text tracks to address #23

### CODE REVIEW

**Comment by mreinstein** [comment]
@shanepoints looks good I think! My only complaint is that like 2/3 of the code in `px-video.js` (lines 275-767) are a big pile of continuous code. Ideally chunks of this logic would be turned into functions. But that's probably better left for a follow up/cleanup PR in my opinion. 

I know this isn't something your PR introduced, just something I'm lamenting in looking at the file with fresh eyes.

@hozefaj thoughts on this?

**Comment by shanepoints** [comment]
@mreinstein, yeah I definitely hold a similar opinion, but figured that code organization/optimization would best be handled in a separate ticket.  I realize, however, that this PR has added some spaghetti to the party, so I would be happy to do some reorganization if it would please the court.  

Do you or @hozefaj have any opinions about introducing a build process so that we can move various responsibilities into their own files?

**Comment by hozefaj** [comment]
> Do you or @hozefaj have any opinions about introducing a build process so that we can move various responsibilities into their own files?

**Comment by shanepoints** [comment]
Cool...  I think @mreinstein is already running with a fork to support integrations with commonjs, scss, etc.., so we should be seeing a PR for that shortly!

As far as this PR, I have been adding better accessibility for the caption selection menu.  I think the last thing is to wire up the arrow keys to that menu. Then I'll run through cross-browser testing and ping you on this thread when it's ready for action.

**Comment by mreinstein** [comment]
@hozefaj would you be willing to grant me rights on the github and npm repos for the video player? I'm happy to help with the maintenance burden. I'm not looking to hijack the project structure or anything, just thought it might be helpful.

much thanks!

**Comment by shanepoints** [comment]
@hozefaj it looks to me like this is ready to merge.  I have identified one issue on Edge where selecting the caption item via keyboard does not hide the menu after the selection is made .  It can still be closed via the 'esc' key, and there are no console errors, so I don't know if this is actually a bug.  Stepping through with the debugger does not yield any clues... the thread just runs through the `hideCaptionsSubMenu` function, but the menu remains visible.  I'll pick it up again tomorrow, if you think it's a significant hangup.

**Comment by hozefaj** [comment]
> @hozefaj would you be willing to grant me rights on the github and npm repos for the video player? I'm happy to help with the maintenance burden. I'm not looking to hijack the project structure or anything, just thought it might be helpful.
> 
> much thanks!

@mreinstein You have been pretty active with making updates to this project. If this were my personal project I would do it. But since its under the the `paypal` organisation I am not sure around the process to allow for maintainers who do not work at `paypal`. Let me check on this. @weboverhauls thoughts?

**Comment by mreinstein** [comment]
@hozefaj no worries regarding the maintainership. If it were someone outside of sellpoints offering t maintain one of our repos I'd have simiilar difficulties, so I realize this would probably be a tough sell given the natural organizational boundaries that exist. :) Mostly I just feel guilt that I'm introducing a burden on you and fellow co-workers, even if these changes are valuable because I know they take time to vett properly.

**Pull request closed without merging**
